<?php

########################################################################
# Extension Manager/Repository config file for ext: "downloads"
#
# Auto generated by Extension Builder 2012-03-12
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Downloads',
	'description' => 'A very simple way to include downloads.',
	'category' => 'plugin',
	'author' => 'Oliver Salzburg',
	'author_email' => 'oliver@hartwig-at.de',
	'author_company' => 'Hartwig Communication & Events',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>